version: '3'

services:

  admin:
    container_name: adminer_container
    image: adminer:4.7.1
    restart: always
    depends_on:
      - db
    ports:
      - 8080:8080

  db:
    container_name: mysql_container
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: 'password'
      MYSQL_USER: 'user'
      MYSQL_PASS: 'password'
    volumes:
      - ./database:/var/lib/mysql
    ports:
      - 3310:3306